/**
 * In-memory cache of reduced thumbnails (PNG bytes), keyed by plot id.
 *
 * Node has no image decoder without native dependencies, so thumbnails are
 * generated by the webview (which has a canvas) and posted back to the
 * extension; this cache is what the view protocol and the persistence layer
 * share. SVG entries never get a thumbnail: the vector data itself is small
 * and scales losslessly.
 */
export class ThumbnailCache {
  private readonly map = new Map<string, Uint8Array>();
  private readonly listeners = new Set<() => void>();

  get(id: string): Uint8Array | undefined {
    return this.map.get(id);
  }

  has(id: string): boolean {
    return this.map.has(id);
  }

  set(id: string, data: Uint8Array): void {
    this.map.set(id, data);
    this.emit();
  }

  /** Drop thumbnails whose plot no longer exists. */
  prune(keep: ReadonlySet<string>): void {
    let changed = false;
    for (const id of [...this.map.keys()]) {
      if (!keep.has(id)) {
        this.map.delete(id);
        changed = true;
      }
    }
    if (changed) {
      this.emit();
    }
  }

  entries(): IterableIterator<[string, Uint8Array]> {
    return this.map.entries();
  }

  onDidChange(listener: () => void): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  private emit(): void {
    for (const listener of this.listeners) {
      listener();
    }
  }
}
