import { randomBytes } from 'node:crypto';
import * as vscode from 'vscode';
import type { DisplayMode, DisplayOptions } from './displayOptions';
import type { HistoryEvent, PlotHistory } from './history';
import { groupIntoRuns } from './runs';
import type { ThumbnailCache } from './thumbnails';
import type { PlotEntry } from './types';

/**
 * One webview attached to the plot history: the sidebar view or an editor
 * panel (gallery or pinned single plot). The history model is the single
 * source of truth; every session is a projection kept in sync through
 * messages and fully re-hydrated on each `ready` handshake (neither
 * WebviewView nor our panels retain context when hidden).
 *
 * To avoid shipping every full-resolution figure on each re-hydration, the
 * state message carries reduced thumbnails plus the full image of the selected
 * entry only; the webview requests other full images on demand. Bitmap
 * thumbnails are generated by the webview (canvas) and posted back; SVG scales
 * losslessly, so its own data serves as thumbnail.
 */

/** 'gallery' follows the history with a thumbnail strip; 'single' pins one entry. */
export type SessionMode = 'gallery' | 'single';

export interface SessionOptions {
  readonly mode: SessionMode;
  /** Entry shown by a 'single' session; ignored in 'gallery' mode. */
  readonly pinnedId?: string;
}

/** What a session needs from its owner besides the model: the sticky notice. */
export interface SessionHost {
  readonly notice: string | undefined;
}

export interface CopyResult {
  readonly ok: boolean;
  readonly error?: string;
}

interface WebviewEntry {
  readonly id: string;
  readonly mime: string;
  readonly source: string;
  readonly timestamp: number;
  /** Reduced preview for the strip; absent when none exists yet. */
  readonly thumbUri?: string;
  /** Full-resolution image; only sent for the selected entry or fresh captures. */
  readonly dataUri?: string;
}

interface DisplayState {
  readonly mode: DisplayMode;
  readonly darkFilter: boolean;
}

/** The figure that opens a run, and that run's 1-based number. */
interface RunLabel {
  readonly id: string;
  readonly run: number;
}

type ToWebviewMessage =
  | {
      readonly type: 'state';
      readonly entries: readonly WebviewEntry[];
      readonly selectedId: string | undefined;
      readonly notice: string | undefined;
      readonly sessionMode: SessionMode;
      readonly display: DisplayState;
      readonly runs: readonly RunLabel[];
    }
  | { readonly type: 'runs'; readonly runs: readonly RunLabel[] }
  | { readonly type: 'display'; readonly display: DisplayState }
  | { readonly type: 'added'; readonly entry: WebviewEntry }
  | { readonly type: 'evicted'; readonly ids: readonly string[] }
  | { readonly type: 'selected'; readonly id: string | undefined }
  | { readonly type: 'cleared' }
  | { readonly type: 'notice'; readonly text: string }
  | { readonly type: 'image'; readonly id: string; readonly dataUri: string }
  | {
      readonly type: 'copy';
      readonly id: string;
      readonly mime: string;
      readonly dataUri: string;
    };

type FromWebviewMessage =
  | { readonly type: 'ready' }
  | { readonly type: 'select'; readonly id: string }
  | { readonly type: 'nav'; readonly direction: 'previous' | 'next' }
  | { readonly type: 'requestImage'; readonly id: string }
  | { readonly type: 'thumbnail'; readonly id: string; readonly dataUri: string }
  | { readonly type: 'copyResult'; readonly ok: boolean; readonly error?: string };

function toDataUri(mime: string, data: Uint8Array): string {
  return `data:${mime};base64,${Buffer.from(data).toString('base64')}`;
}

const THUMBNAIL_URI_PREFIX = 'data:image/png;base64,';

/** Uniform user feedback after a clipboard round-trip, shared by all surfaces. */
export function reportCopyResult(result: CopyResult): void {
  if (result.ok) {
    vscode.window.setStatusBarMessage('Plot copied to clipboard', 3000);
  } else {
    void vscode.window.showErrorMessage(
      `Plot Panel: copy failed: ${result.error ?? 'unknown error'}`,
    );
  }
}

export class PlotWebviewSession implements vscode.Disposable {
  private webviewReady = false;
  private disposed = false;
  private pendingCopy: ((result: CopyResult) => void) | undefined;
  private readonly disposables: vscode.Disposable[] = [];
  private readonly disposeListeners = new Set<() => void>();

  constructor(
    private readonly webview: vscode.Webview,
    private readonly extensionUri: vscode.Uri,
    private readonly history: PlotHistory,
    private readonly thumbnails: ThumbnailCache,
    private readonly display: DisplayOptions,
    private readonly host: SessionHost,
    private readonly options: SessionOptions,
  ) {
    webview.options = {
      enableScripts: true,
      localResourceRoots: [vscode.Uri.joinPath(extensionUri, 'media')],
    };
    webview.html = this.renderHtml();
    this.disposables.push(
      webview.onDidReceiveMessage((message: FromWebviewMessage) => this.onMessage(message)),
    );
    const unsubscribe = this.history.onDidChange((event) => this.onHistoryEvent(event));
    this.disposables.push(new vscode.Disposable(unsubscribe));
    const unsubscribeDisplay = this.display.onDidChange(() =>
      this.post({ type: 'display', display: this.displayState() }),
    );
    this.disposables.push(new vscode.Disposable(unsubscribeDisplay));
  }

  private displayState(): DisplayState {
    return { mode: this.display.mode, darkFilter: this.display.darkFilter };
  }

  get mode(): SessionMode {
    return this.options.mode;
  }

  get pinnedId(): string | undefined {
    return this.options.pinnedId;
  }

  /** Register a callback for when the session is disposed (used by the registry). */
  onDidDispose(listener: () => void): void {
    this.disposeListeners.add(listener);
  }

  /** Wait for the webview to complete the ready handshake. */
  async whenReady(timeoutMs: number): Promise<boolean> {
    const deadline = Date.now() + timeoutMs;
    while (!this.webviewReady) {
      if (this.disposed || Date.now() > deadline) {
        return false;
      }
      await new Promise((resolve) => setTimeout(resolve, 50));
    }
    return true;
  }

  /** Explicit message for outputs that cannot be captured (interactive widgets). */
  showNotice(text: string): void {
    this.post({ type: 'notice', text });
  }

  /**
   * Copy a figure to the clipboard as PNG. The stable extension API
   * (vscode.env.clipboard) is text-only, so the write happens in the webview
   * via navigator.clipboard; the caller must focus the webview first because
   * the browser clipboard requires a focused document.
   */
  copy(entry: PlotEntry): Promise<CopyResult> {
    return new Promise<CopyResult>((resolve) => {
      this.pendingCopy = resolve;
      this.post({
        type: 'copy',
        id: entry.id,
        mime: entry.mime,
        dataUri: toDataUri(entry.mime, entry.data),
      });
      setTimeout(() => {
        if (this.pendingCopy === resolve) {
          this.pendingCopy = undefined;
          resolve({ ok: false, error: 'timed out' });
        }
      }, 5000);
    });
  }

  private toWebviewEntry(entry: PlotEntry, includeData: boolean): WebviewEntry {
    const base = {
      id: entry.id,
      mime: entry.mime,
      source: entry.source,
      timestamp: entry.timestamp,
    };
    const thumb = this.thumbnails.get(entry.id);
    return {
      ...base,
      // SVG is its own thumbnail: small and lossless at any size.
      ...(entry.mime === 'image/svg+xml'
        ? { thumbUri: toDataUri(entry.mime, entry.data) }
        : thumb !== undefined
          ? { thumbUri: toDataUri('image/png', thumb) }
          : {}),
      ...(includeData ? { dataUri: toDataUri(entry.mime, entry.data) } : {}),
    };
  }

  /**
   * Which figure opens which run, recomputed from the whole history every
   * time it changes. Freezing this onto each entry as it arrived went stale
   * the moment the oldest entries were evicted: the figure carrying a run's
   * label could be dropped, and the run lost its marker.
   */
  private runLabels(): readonly RunLabel[] {
    const labels: RunLabel[] = [];
    const entries = this.history.entries;
    for (const group of groupIntoRuns(entries)) {
      const first = entries[group.startIndex];
      if (first !== undefined) {
        labels.push({ id: first.id, run: group.run });
      }
    }
    return labels;
  }

  private postRunLabels(): void {
    if (this.options.mode === 'gallery') {
      this.post({ type: 'runs', runs: this.runLabels() });
    }
  }

  private onHistoryEvent(event: HistoryEvent): void {
    switch (event.type) {
      case 'added':
        if (this.options.mode === 'gallery') {
          // Fresh captures ship with full data: the webview must display them
          // and derive the thumbnail.
          this.post({ type: 'added', entry: this.toWebviewEntry(event.entry, true) });
          this.postRunLabels();
        } else if (event.entry.id === this.options.pinnedId) {
          // A revived single panel can hydrate before the persisted history
          // is restored; re-send its state once the pinned entry appears.
          this.sendState();
        }
        break;
      case 'evicted':
        this.post({ type: 'evicted', ids: event.ids });
        this.postRunLabels();
        break;
      case 'selected':
        if (this.options.mode === 'gallery') {
          this.post({ type: 'selected', id: event.id });
        }
        break;
      case 'cleared':
        this.post({ type: 'cleared' });
        break;
    }
  }

  private sendState(): void {
    if (this.options.mode === 'single') {
      const pinned =
        this.options.pinnedId === undefined
          ? undefined
          : this.history.entries.find((entry) => entry.id === this.options.pinnedId);
      this.post({
        type: 'state',
        entries: pinned === undefined ? [] : [this.toWebviewEntry(pinned, true)],
        selectedId: pinned?.id,
        notice: pinned === undefined ? 'This plot was removed from the history.' : undefined,
        sessionMode: 'single',
        display: this.displayState(),
        runs: [],
      });
      return;
    }
    const selectedId = this.history.selected?.id;
    this.post({
      type: 'state',
      entries: this.history.entries.map((entry) =>
        this.toWebviewEntry(entry, entry.id === selectedId),
      ),
      selectedId,
      notice: this.host.notice,
      sessionMode: 'gallery',
      display: this.displayState(),
      runs: this.runLabels(),
    });
  }

  private onMessage(message: FromWebviewMessage): void {
    switch (message.type) {
      case 'ready':
        this.webviewReady = true;
        this.sendState();
        break;
      case 'select':
        this.history.select(message.id);
        break;
      case 'nav':
        if (message.direction === 'previous') {
          this.history.previous();
        } else {
          this.history.next();
        }
        break;
      case 'requestImage': {
        const entry = this.history.entries.find((candidate) => candidate.id === message.id);
        if (entry !== undefined) {
          this.post({
            type: 'image',
            id: entry.id,
            dataUri: toDataUri(entry.mime, entry.data),
          });
        }
        break;
      }
      case 'thumbnail': {
        // Only store thumbnails for plots that still exist, and only PNG.
        // Several sessions may derive the same thumbnail concurrently; the
        // first reply wins so the cache emits (and persistence syncs) once.
        if (!message.dataUri.startsWith(THUMBNAIL_URI_PREFIX)) {
          break;
        }
        if (this.thumbnails.has(message.id)) {
          break;
        }
        const exists = this.history.entries.some((candidate) => candidate.id === message.id);
        if (!exists) {
          break;
        }
        this.thumbnails.set(
          message.id,
          Buffer.from(message.dataUri.slice(THUMBNAIL_URI_PREFIX.length), 'base64'),
        );
        break;
      }
      case 'copyResult': {
        const pending = this.pendingCopy;
        this.pendingCopy = undefined;
        pending?.(message.error === undefined ? { ok: message.ok } : message);
        break;
      }
    }
  }

  private post(message: ToWebviewMessage): void {
    if (!this.disposed) {
      void this.webview.postMessage(message);
    }
  }

  private renderHtml(): string {
    const nonce = randomBytes(16).toString('hex');
    const scriptUri = this.webview.asWebviewUri(
      vscode.Uri.joinPath(this.extensionUri, 'media', 'main.js'),
    );
    const styleUri = this.webview.asWebviewUri(
      vscode.Uri.joinPath(this.extensionUri, 'media', 'main.css'),
    );
    // Static skeleton only: all dynamic content is built by main.js through
    // DOM APIs, never through interpolated HTML.
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Security-Policy"
        content="default-src 'none'; img-src data:; style-src ${this.webview.cspSource}; script-src 'nonce-${nonce}';">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="${styleUri}">
  <title>Plots</title>
</head>
<body>
  <main id="stage">
    <img id="figure" alt="Current plot" hidden>
    <p id="empty">No plots yet. Figures from notebooks and the Interactive Window appear here automatically.</p>
  </main>
  <p id="notice" role="status" hidden></p>
  <nav id="strip" role="listbox" aria-label="Plot history" hidden></nav>
  <script nonce="${nonce}" src="${scriptUri}"></script>
</body>
</html>`;
  }

  dispose(): void {
    if (this.disposed) {
      return;
    }
    this.disposed = true;
    for (const disposable of this.disposables) {
      disposable.dispose();
    }
    this.disposables.length = 0;
    const pending = this.pendingCopy;
    this.pendingCopy = undefined;
    pending?.({ ok: false, error: 'the view was closed' });
    for (const listener of this.disposeListeners) {
      listener();
    }
    this.disposeListeners.clear();
  }
}
